spring.application.name=my-web-project

#JWT\uc124\uc815
#secret: \ucd5c\uc18c 32\uc790 \uc774\uc0c1\uc758 \ub79c\ub364 \ubb38\uc790\uc5f4 (\ubcf4\uc548\uc744 \uc704\ud574 \ubcf5\uc7a1\ud558\uac8c \uc791\uc131\ud558\ub294\uac8c \uc88b\uc74c)
#\ud1a0\ud070\uc758 \uc11c\uba85\uc744 \ucc0d\uc744 \ub54c \uc0ac\uc6a9\ud558\ub294 \ube44\ubc00\ubc88\ud638\uc774\uace0, \uc774 \uac12\uc774 \ubc14\ub00c\uba74 \uc774\uc804\uc5d0 \ubc1c\ud589\ub41c \ud1a0\ud070\ub4e4\uc740 \ubaa8\ub450 \uac00\uc9dc \ucde8\uae09\ubc1b\uc74c
#\uc11c\ubc84\ub9cc \uc54c\uace0 \uc788\ub294 \ube44\ubc00 \ud0a4
#\uacb0\ub860\uc740 \ud1a0\ud070\uac12 \ud574\ub354.\ud398\uc774\ub85c\ub4dc.\uc11c\uba85 \uc911\uc5d0\uc11c \uc774 \ud0a4\ub294 \ud398\uc774\ub85c\ub4dc\uc640 \uc11c\uba85\uc5d0 \uc7ac\ub8cc\ub85c \uc4f0\uc77c \uc554\ud638\ud654\uc6a9 \ube44\ubc00\ubc88\ud638(\ube44\ubc00\ud0a4)
jwt.secret=vmfhaltiraostjtjdfhqordlfmaduTspsswjdfhffkrhfoVJswpsvmfmghasdfasdf

#expiration: 3600000(1\uc2dc\uac04)
#\ubc1c\ud589\ub41c(Access Token) \ud1a0\ud070 \uc720\ud6a8\uae30\uac04
jwt.expiration=10000
#jwt.expiration=3600000

#refresh-expiration: 1209600000(2\uc8fc)
#\ubc1c\ud589\ub41c(Refresh Token) \ud1a0\ud070 \uc720\ud6a8\uae30\uac04
jwt.refresh-expiration=1209600000
#jwt.refresh-expiration=604800000

#[\uc624\ub77c\ud074 \uc811\uc18d \uc815\ubcf4]
####################################################################
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@10.218.1.112:1522:ORA10
spring.datasource.username=demaweb
spring.datasource.password=demaweb
####################################################################

#[JPA \uc124\uc815]
####################################################################
#\uc790\ubc14\ucf54\ub4dc\ub97c \ubcf4\uace0 \ud14c\uc774\ube14\uc744 \uc790\ub3d9\uc73c\ub85c \ub9cc\ub4e4\uac70\ub098 \uc218\uc815\ud574\uc90c(\ud575\uc2ec!)
spring.jpa.hibernate.ddl-auto=update
#\uc11c\ubc84\uc2e4\ud589\uc2dc \ucf58\uc194\uc5d0 \uc2e4\uc81c \ub0a0\uc544\uac00\ub294 SQL\ubb38\uc744 \ubcf4\uc5ec\uc90c
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
#\uc624\ub77c\ud074 \uc804\uc6a9 \ubb38\ubc95 \uc0ac\uc6a9
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
#consol\ub85c\uadf8\uc5d0 hibernate\ucffc\ub9ac\uc5d0 \uac12\uc5d0 \ubb3c\uc74c\ud45c(?)\ub300\uc2e0 \ub370\uc774\ud130\ub85c \ubcf4\uae30
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
####################################################################